export const MESSAGE = {
  LOGIN_SUCCESS: "Login successful",
  USER_REGISTERED: "User registration successful",
  VERIFY_NUMBER: "Please verify your phone number to continue",
  FIELDS_REQUIRED: "All fields are required",
  USER_EXISTS: "User already exists",
  EMAIL_NOT_FOUND: "Email does not exist",
  INVALID_PASSWORD: "Invalid password",
  INVALID_NUMBER: "Phone number should be of 10 digits",
  INVALID_OTP: "Invalid OTP",
  OTP_SENT: "OTP sent successfully",
  INVALID_OTP: "Invalid OTP",
  ENTER_OTP: "Please Enter a 6 digit OTP",
  PHONE_VERIFICATION: "Number verification successful",
  SOMETHING_WRONG: "Something went wrong!",
  USER_PROFILE: "User profile data",
  USER_NOT_FOUND: "User not found",
  PHONE_EXISTS: "Number already in use",
  LOGIN_ERROR: "Invalid email or password",
  SYMBOL_EMPTY: "Symbol could not be empty",
  SYMBOL_ADDED: "Symbol added successfully",
  SYMBOL_ALREADY_EXISTS: "Symbol already exists",
  WATCH_LIST_DATA: "Watch list data",
  SYMBOL_REMOVED: "Symbol removed successfully",
  SYMBOL_NOT_FOUND: "Symbol not found",
  BOUGHT_STOCK: "Stock bought successfully!",
  BOUGHT_STOCK_FAILED: "Failed to buy this stock",
  USER_STOCK_DATA: "My stock data",
  USER_STOCK_DATA_NOT_FOUND: "User stock data not found",
  SELL_STOCK: "Stock sold!",
  QUANTITY_ERROR: "Cannot sell more than existing quantity",
  STOCK_SQUARE_OFF: "Stock squared off",
  ALREADY_SQUARED: "Stock Already squared off!",
  ADDED_IN_QUEUE:
    "Order Placed",
  // ADDED_IN_QUEUE:
  //   "Stock added in queue!, will be bought once it matches the given price else amount will be refunded",
  ITRADAY_ERROR: "Intraday is only available from 9:15 AM to 3:20 PM",
  INSUFFICIENT_FUNDS: "Insufficient funds",
  NOT_EXECUTED: "Stock not executed yet. Cannot sqaure off!",
  OUT_OF_TIME_SQUARE: "Cannot sqaure off because the intraday time has passed",
  INVALID_STOCK: "Invalid stock",
  INVALID_STOCK_TYPE: "Invalid stock type",
  INVALID_TYPE: "Invalid type",
  SELL_ERROR: "Sell only works in intraday",
  DECODED_DATA: "Decoded stock data",
  STOCK_NOT_FOUND: "Stock not found",
  INVALID_STOCK_STATUS: "Stocks can be cancelled only in pending state",
  STOCK_DELETED: "Stock cancelled successfully",
  FIELDS_REQUIRED: "All fields are required.",
  USER_NOT_FOUND: "User not found.",
  LOGIN_ERROR: "Invalid email or password.",
  LOGIN_SUCCESS: "Login successful.",
  ADMIN_CREATED: "Admin created successfully.",
  ADMINS_FETCHED: "Admins fetched successfully.",
  STATUS_UPDATED: "Admin status updated successfully.",
  PASSWORD_RESET: "Password reset successfully.",
  ADMIN_NOT_FOUND: "Admin not found.",
  ADMIN_DELETED: "Admin deleted successfully.",
  SUPER_ADMIN_CREATED: "Super admin created successfully.",
  SUPER_ADMIN_EXISTS: "Super admin already exists.",
  INTRO_NOT_FOUND: 'Intro Slider data not found',
  INTERNAL_ERROR: 'Internal server error',
};
